### PR TITLE
Make sure we pass start sector as int to pyparted not as Decimal

### PR DESCRIPTION
**Pull request by vojtechtrefny**

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
Jenkins, test this please.

**Comment by vojtechtrefny** [comment]
The run on F34 is not finished because the session is killed by OOM killer (pylint is using  more than 4 GiB of memory). This happens on master too so it's not related to this change.

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Pull request merged**
